
const CountryArr = [
    "Afghanistan",
    "American Samoa",
    "Andorra",
    "Angola",
    "Australia",
    "Azerbaijan",
    "Bahrain",
    "Bangladesh",
    "Bermuda",
    "Brazil",
    "British Indian Ocean Territory (the)",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Canada",
    "Central African Republic (the)",
    "Egypt",
    "Fiji",
    "Finland",
    "France",
    "Germany",
    "Ghana",
    "Greece",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Korea (the Democratic People's Republic of)",
    "Korea (the Republic of)",
    "Kuwait",
    "Malaysia",
    "Mexico",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands (the)",
    "New Zealand",
    "Norfolk Island",
    "Northern Mariana Islands (the)",
    "Norway",
    "Oman",
    "Pakistan",
    "Philippines (the)",
    "Poland",
    "Portugal",
    "Qatar",
    "Russian Federation (the)",
    "Saudi Arabia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Turkey",
    "Turkmenistan",
    "Ukraine",
    "United Arab Emirates (UAE)",
    "United Kingdom",
    "United State",
    "Uruguay",
    "Uzbekistan",
    "Viet Nam",
    "Yemen",
    "Zimbabwe",
];

export default CountryArr;
