import { product6, product2, product4, product8 } from '@common';
import { I18nManager } from 'react-native';
const DealProductDummy = [
    { id: "5", image: product4, name: I18nManager.isRTL ? 'قميص للرجال' : 'Men Shirt', price: '$200', off: '10% Off', rating: 5, new: false, isFav: true, out_of_stock: false, reviewCount: 100, sizes: [6, 7, 8.5, 32, 36], description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc." },
    { id: "9", image: product6, name: I18nManager.isRTL ? 'حذاء رجالي أزرق' : 'Men Blue Shoes', price: '$200', special: true, off: '10% Off', specialPrice: '$150', rating: 5, new: false, isFav: true, out_of_stock: false },
    { id: "10", image: product2, name: I18nManager.isRTL ? 'حذاء رياضي برتقالي للرجال' : 'Men Orange Sport Shoes', price: '$450', special: true, specialPrice: '$300', off: '20% Off', rating: 4, new: false, isFav: false, out_of_stock: false },
    { id: "6", image: product8, name: I18nManager.isRTL ? 'بخاخ الجسم أكس' : 'AXE body Spray', price: '$450', off: '20% Off', rating: 4, new: false, isFav: false, out_of_stock: false, reviewCount: 100, sizes: [6, 7, 8.5, 32, 36], description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc." },
];

export default DealProductDummy;
